"""Independently delivered plans must not be lost to unproven equivalence.

Synthetic in-memory fixtures only. No clinical data. Every plan, dose, record
and structure set is generated by the reference-chain helpers with fresh UIDs.

Two historical defects in ``_classify_approved_doses`` are covered.

1. Equal prescription and fraction signatures were treated as revisions even
   when each plan carried its own disjoint RTRECORD sessions, so one delivered
   plan silently left ``selected_plans``.
2. A supported plan whose validated treatment dates were a strict subset of
   another plan's dates was excluded outright.

The repair retains every independently delivered plan as selected membership
while withholding a course dose grid, course prescription scalars and
dose-response eligibility until the course semantics are reconciled. It does
not sum unrelated prescriptions, add fractions across concurrent targets, or
grant readiness.
"""
from __future__ import annotations

import json
from datetime import date, timedelta
from pathlib import Path

import pydicom
import pytest
from pydicom.dataset import Dataset
from pydicom.sequence import Sequence
from pydicom.uid import generate_uid

from rtpipeline import organize as org
from rtpipeline.config import PipelineConfig
from rtpipeline.course_contract import load_course_contract
from rtpipeline.organize_ledger import read_organize_ledger
from rtpipeline.plan_disposition import RELATIVE_PATH
from synthetic_rt_fixtures import (
    make_dose as _mk_dose,
    make_plan as _mk_plan,
    make_record as _mk_record,
    make_struct as _mk_struct,
)

UNRECONCILED = "independent_delivered_plans_unreconciled"


def _set_isocentre(path: Path, position: tuple[float, float, float]) -> None:
    """Attach a minimal isocentre, not enough to prove physical equivalence.

    Strict-proof controls later replace this with the fuller beam fixture.
    """
    ds = pydicom.dcmread(str(path))
    control_point = Dataset()
    control_point.ControlPointIndex = 0
    control_point.IsocenterPosition = [float(value) for value in position]
    ds.BeamSequence[0].ControlPointSequence = Sequence([control_point])
    ds.save_as(str(path), enforce_file_format=True)


def _plan_and_dose(
    root: Path,
    name: str,
    *,
    struct_uid: str,
    study_uid: str,
    frame_uid: str,
    plan_date: str,
    rx_gy: float,
    fractions: int,
    isocentre: tuple[float, float, float],
    plan_uid: str | None = None,
    with_pixels: bool = False,
) -> tuple[Path, Path, str]:
    plan_uid = plan_uid or generate_uid()
    plan = _mk_plan(
        root / f"{name}_plan.dcm",
        plan_uid,
        struct_uid=struct_uid,
        study_uid=study_uid,
        frame_uid=frame_uid,
        date=plan_date,
        rx_gy=rx_gy,
        fractions=fractions,
        label=name,
    )
    _set_isocentre(plan, isocentre)
    dose = _mk_dose(
        root / f"{name}_dose.dcm",
        generate_uid(),
        plan_uid=plan_uid,
        study_uid=study_uid,
        frame_uid=frame_uid,
        with_pixels=with_pixels,
    )
    return plan, dose, plan_uid


def _records(
    root: Path, prefix: str, plan_uid: str, count: int, *, start: date
) -> list[Path]:
    return [
        _mk_record(
            root / f"{prefix}_{index:02d}.dcm",
            plan_uid,
            date=(start + timedelta(days=index)).strftime("%Y%m%d"),
        )
        for index in range(count)
    ]


def _record_referencing_both(root: Path, name: str, uids: list[str], *, day: date) -> Path:
    path = _mk_record(root / f"{name}.dcm", uids[0], date=day.strftime("%Y%m%d"))
    ds = pydicom.dcmread(str(path))
    for uid in uids[1:]:
        ref = Dataset()
        ref.ReferencedSOPClassUID = ds.ReferencedRTPlanSequence[0].ReferencedSOPClassUID
        ref.ReferencedSOPInstanceUID = uid
        ds.ReferencedRTPlanSequence.append(ref)
    ds.save_as(str(path), enforce_file_format=True)
    return path


def _ids() -> tuple[str, str, str]:
    return generate_uid(), generate_uid(), generate_uid()


def _physical_beam(path: Path, *, isocentre: tuple[float, float, float], machine: str = "SYNTHETIC_LINAC") -> None:
    """Give the single TREATMENT beam the complete source evidence the strict
    proof reads: machine, positive meterset, two control points carrying the
    gantry/collimator/couch/energy axes and the isocentre. Without these the
    plan cannot be proven equivalent to anything."""
    ds = pydicom.dcmread(str(path))
    beam = ds.BeamSequence[0]
    beam.TreatmentMachineName = machine
    beam.BeamName = "field1"
    control_points = []
    for index in range(2):
        control_point = Dataset()
        control_point.ControlPointIndex = index
        control_point.CumulativeMetersetWeight = float(index)
        control_point.GantryAngle = 0.0
        control_point.BeamLimitingDeviceAngle = 0.0
        control_point.PatientSupportAngle = 0.0
        control_point.NominalBeamEnergy = 6.0
        control_point.IsocenterPosition = [float(value) for value in isocentre]
        control_points.append(control_point)
    beam.ControlPointSequence = Sequence(control_points)
    beam.NumberOfControlPoints = 2
    ds.FractionGroupSequence[0].ReferencedBeamSequence[0].BeamMeterset = 200.0
    ds.save_as(str(path), enforce_file_format=True)


def _strict_equivalent_copy(root: Path, source: Path, label: str, *, plan_date: str = "20240102") -> tuple[Path, Path, str]:
    """Re-export the same physical plan under a new SOPInstanceUID.

    Only identity and naming change (SOPInstanceUID, label, name, beam name,
    plan date). Target dose references, fraction groups, machine, meterset,
    beam dose, control points and isocentre stay byte-equal, which is the
    evidence the strict proof requires. Returns plan path, dose path, UID.
    """
    ds = pydicom.dcmread(str(source))
    new_uid = generate_uid()
    ds.SOPInstanceUID = new_uid
    ds.file_meta.MediaStorageSOPInstanceUID = new_uid
    ds.RTPlanLabel = label
    ds.RTPlanName = label
    ds.RTPlanDate = plan_date
    ds.BeamSequence[0].BeamName = label
    plan = root / f"{label}_plan.dcm"
    ds.save_as(str(plan), enforce_file_format=True)
    dose = _mk_dose(
        root / f"{label}_dose.dcm", generate_uid(), plan_uid=new_uid,
        study_uid=str(ds.StudyInstanceUID), frame_uid=str(ds.FrameOfReferenceUID),
    )
    return plan, dose, new_uid


def _assert_unreconciled(classified, plans: list[Path]) -> None:
    assert classified.classification == UNRECONCILED
    assert sorted(map(str, classified.selected_plans)) == sorted(map(str, plans))
    assert classified.selected_doses == []
    assert classified.should_sum is False
    assert classified.prescription_plans == []
    assert any("reconcil" in warning.lower() for warning in classified.warnings)


# --- Defect 1: equal Rx/fx signatures with independent delivery ---------------


def test_equal_signature_independent_deliveries_on_the_same_dates_are_retained(tmp_path):
    """Two 25 Gy / 5 fx plans, distinct isocentres, disjoint records, same dates."""
    study_uid, frame_uid, struct_uid = _ids()
    left_plan, left_dose, left_uid = _plan_and_dose(
        tmp_path, "left", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    right_plan, right_dose, right_uid = _plan_and_dose(
        tmp_path, "right", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(233.0, 0.0, 0.0),
    )
    records = _records(tmp_path, "left_rec", left_uid, 5, start=date(2024, 1, 8))
    records += _records(tmp_path, "right_rec", right_uid, 5, start=date(2024, 1, 8))

    classified = org._classify_doses(
        [left_plan, right_plan], [left_dose, right_dose], treatment_record_paths=records
    )

    _assert_unreconciled(classified, [left_plan, right_plan])
    assert sorted(map(str, classified.excluded_doses)) == sorted(map(str, [left_dose, right_dose]))
    assert not any("De-duplicated" in warning for warning in classified.warnings)


def test_equal_signature_independent_deliveries_on_sequential_dates_are_retained(tmp_path):
    """Equal 30 Gy / 10 fx plans delivered in two disjoint date blocks."""
    study_uid, frame_uid, struct_uid = _ids()
    first_plan, first_dose, first_uid = _plan_and_dose(
        tmp_path, "first", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=30.0, fractions=10, isocentre=(0.0, 0.0, 0.0),
    )
    second_plan, second_dose, second_uid = _plan_and_dose(
        tmp_path, "second", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240301", rx_gy=30.0, fractions=10, isocentre=(0.0, 0.0, 475.0),
    )
    records = _records(tmp_path, "first_rec", first_uid, 10, start=date(2024, 1, 8))
    records += _records(tmp_path, "second_rec", second_uid, 10, start=date(2024, 3, 4))

    classified = org._classify_doses(
        [first_plan, second_plan], [first_dose, second_dose], treatment_record_paths=records
    )

    _assert_unreconciled(classified, [first_plan, second_plan])


# --- Defect 2: strict-subset treatment dates ----------------------------------


def test_unequal_signature_with_strict_subset_dates_and_distinct_isocentre_retains_both(tmp_path):
    """3 x 9 Gy delivered inside the window of 5 x 5 Gy, 233 mm apart."""
    study_uid, frame_uid, struct_uid = _ids()
    five_plan, five_dose, five_uid = _plan_and_dose(
        tmp_path, "five", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    three_plan, three_dose, three_uid = _plan_and_dose(
        tmp_path, "three", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=27.0, fractions=3, isocentre=(233.0, 0.0, 0.0),
    )
    records = _records(tmp_path, "five_rec", five_uid, 5, start=date(2024, 1, 8))
    records += _records(tmp_path, "three_rec", three_uid, 3, start=date(2024, 1, 9))

    classified = org._classify_doses(
        [five_plan, three_plan], [five_dose, three_dose], treatment_record_paths=records
    )

    _assert_unreconciled(classified, [five_plan, three_plan])
    assert not any(
        warning.startswith("Excluded plan") and "strict subset" in warning
        for warning in classified.warnings
    )


def test_small_prescription_same_isocentre_remains_unresolved_not_qa(tmp_path):
    """A 2 Gy / 1 fx opposed-field plan on a shared isocentre is not auto-excluded."""
    study_uid, frame_uid, struct_uid = _ids()
    main_plan, main_dose, main_uid = _plan_and_dose(
        tmp_path, "main", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(10.0, 20.0, 30.0),
    )
    small_plan, small_dose, small_uid = _plan_and_dose(
        tmp_path, "small", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=2.0, fractions=1, isocentre=(10.0, 20.0, 30.0),
    )
    records = _records(tmp_path, "main_rec", main_uid, 5, start=date(2024, 1, 8))
    records += _records(tmp_path, "small_rec", small_uid, 1, start=date(2024, 1, 10))

    classified = org._classify_doses(
        [main_plan, small_plan], [main_dose, small_dose], treatment_record_paths=records
    )

    _assert_unreconciled(classified, [main_plan, small_plan])
    joined = " ".join(classified.warnings).lower()
    assert "verification" not in joined and "qa" not in joined.split()


# --- Controls that must hold before and after the repair ----------------------


def test_exact_same_uid_duplicate_file_is_harmless(tmp_path):
    study_uid, frame_uid, struct_uid = _ids()
    plan_uid = generate_uid()
    plan_a, dose, _ = _plan_and_dose(
        tmp_path, "copy_a", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0), plan_uid=plan_uid,
    )
    plan_b = tmp_path / "copy_b_plan.dcm"
    plan_b.write_bytes(plan_a.read_bytes())
    records = _records(tmp_path, "rec", plan_uid, 5, start=date(2024, 1, 8))

    classified = org._classify_doses([plan_a, plan_b], [dose], treatment_record_paths=records)

    assert classified.classification == "plan_revisions_deduplicated"
    assert len(classified.selected_plans) == 1
    assert classified.selected_doses == [dose]
    assert classified.should_sum is False


def test_undelivered_later_revision_cannot_erase_the_delivered_plan(tmp_path):
    study_uid, frame_uid, struct_uid = _ids()
    delivered_plan, delivered_dose, delivered_uid = _plan_and_dose(
        tmp_path, "delivered", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    revision_plan, revision_dose, _ = _plan_and_dose(
        tmp_path, "revision", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240201", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    records = _records(tmp_path, "rec", delivered_uid, 5, start=date(2024, 1, 8))

    classified = org._classify_doses(
        [delivered_plan, revision_plan], [delivered_dose, revision_dose], treatment_record_paths=records
    )

    assert classified.classification == "plan_revisions_deduplicated"
    assert classified.selected_plans == [delivered_plan]
    assert classified.selected_doses == [delivered_dose]
    assert classified.excluded_doses == [revision_dose]


def test_records_referencing_both_equal_plans_without_physical_proof_are_held(tmp_path):
    """A record naming two plans is not permission to erase one.

    Both plans share prescription, fractions, structure set, frame of
    reference and every delivery record, but carry no machine, meterset or
    control-point evidence, so physical equivalence cannot be proven. Both
    remain membership under the unreconciled hold.
    """
    study_uid, frame_uid, struct_uid = _ids()
    plan_a, dose_a, uid_a = _plan_and_dose(
        tmp_path, "a", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    plan_b, dose_b, uid_b = _plan_and_dose(
        tmp_path, "b", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240102", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    records = [
        _record_referencing_both(tmp_path, f"joint_{index}", [uid_a, uid_b], day=date(2024, 1, 8) + timedelta(days=index))
        for index in range(5)
    ]

    classified = org._classify_doses([plan_a, plan_b], [dose_a, dose_b], treatment_record_paths=records)

    _assert_unreconciled(classified, [plan_a, plan_b])
    assert not any("De-duplicated" in warning for warning in classified.warnings)
    assert any("not proven physically equivalent" in warning for warning in classified.warnings)


def test_records_referencing_both_plans_with_strict_physical_proof_deduplicate(tmp_path):
    """Positive control: an alternate-UID re-export of the same physical plan,
    named by every record together with the original, contributes once."""
    study_uid, frame_uid, struct_uid = _ids()
    plan_a, dose_a, uid_a = _plan_and_dose(
        tmp_path, "a", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(10.0, 20.0, 30.0),
    )
    _physical_beam(plan_a, isocentre=(10.0, 20.0, 30.0))
    plan_b, dose_b, uid_b = _strict_equivalent_copy(tmp_path, plan_a, "b")
    records = [
        _record_referencing_both(tmp_path, f"joint_{index}", [uid_a, uid_b], day=date(2024, 1, 8) + timedelta(days=index))
        for index in range(5)
    ]

    classified = org._classify_doses([plan_a, plan_b], [dose_a, dose_b], treatment_record_paths=records)

    assert classified.classification == "plan_revisions_deduplicated"
    # Both plans cover every record; the later-dated proven-identical
    # re-export is the representative, as for any equal revision pair.
    assert classified.selected_plans == [plan_b]
    assert classified.selected_doses == [dose_b]
    assert classified.excluded_doses == [dose_a]
    assert classified.should_sum is False


def test_source_supported_replacement_partition_still_selects_delivered_parts(tmp_path):
    study_uid, frame_uid, struct_uid = _ids()
    total_plan, total_dose, _ = _plan_and_dose(
        tmp_path, "total", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20010101", rx_gy=39.0, fractions=13, isocentre=(0.0, 0.0, 0.0),
    )
    part1_plan, part1_dose, part1_uid = _plan_and_dose(
        tmp_path, "part1", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20010102", rx_gy=24.0, fractions=8, isocentre=(0.0, 0.0, 0.0),
    )
    part2_plan, part2_dose, part2_uid = _plan_and_dose(
        tmp_path, "part2", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20010103", rx_gy=15.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    records = _records(tmp_path, "p1", part1_uid, 8, start=date(2001, 1, 5))
    records += _records(tmp_path, "p2", part2_uid, 5, start=date(2001, 1, 20))

    classified = org._classify_doses(
        [total_plan, part1_plan, part2_plan],
        [total_dose, part1_dose, part2_dose],
        treatment_record_paths=records,
    )

    assert classified.classification == "replacement_course_total"
    assert classified.selected_plans == [part1_plan, part2_plan]
    assert classified.selected_doses == [part1_dose, part2_dose]
    assert classified.should_sum is True


def test_source_supported_delivered_remainder_chain_still_accumulates(tmp_path):
    study_uid, frame_uid, struct_uid = _ids()
    total_plan, total_dose, total_uid = _plan_and_dose(
        tmp_path, "course_total", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20020201", rx_gy=39.0, fractions=13, isocentre=(0.0, 0.0, 0.0),
    )
    remainder_plan, remainder_dose, remainder_uid = _plan_and_dose(
        tmp_path, "remainder", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20020215", rx_gy=30.0, fractions=10, isocentre=(0.0, 0.0, 0.0),
    )
    records = _records(tmp_path, "initial", total_uid, 2, start=date(2002, 2, 5))
    records += _records(tmp_path, "rem", remainder_uid, 10, start=date(2002, 2, 16))

    classified = org._classify_doses(
        [total_plan, remainder_plan], [total_dose, remainder_dose], treatment_record_paths=records
    )

    assert classified.classification == "delivered_remainder_plan_doses_accumulated"
    assert classified.selected_plans == [total_plan, remainder_plan]
    assert classified.selected_doses == [total_dose, remainder_dose]
    assert classified.should_sum is True


def test_sequential_boost_with_disjoint_dates_still_sums(tmp_path):
    study_uid, frame_uid, struct_uid = _ids()
    phase1_plan, phase1_dose, phase1_uid = _plan_and_dose(
        tmp_path, "phase1", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=50.0, fractions=25, isocentre=(0.0, 0.0, 0.0),
    )
    phase2_plan, phase2_dose, phase2_uid = _plan_and_dose(
        tmp_path, "phase2", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240205", rx_gy=10.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    records = _records(tmp_path, "ph1", phase1_uid, 25, start=date(2024, 1, 1))
    records += _records(tmp_path, "ph2", phase2_uid, 5, start=date(2024, 2, 5))

    classified = org._classify_doses(
        [phase1_plan, phase2_plan], [phase1_dose, phase2_dose], treatment_record_paths=records
    )

    assert classified.classification == "sequential_phases_summed"
    assert classified.selected_plans == [phase1_plan, phase2_plan]
    assert classified.should_sum is True


# --- Production interface: organizer publication ------------------------------


def _run_organizer(root: Path, out: Path):
    config = PipelineConfig(
        root,
        out,
        out.parent / "logs",
        max_workers_override=1,
        dicom_copy_use_hardlinks=False,
        dicom_copy_dedup_by_sop_uid=False,
    )
    courses = org.organize_and_merge(config)
    dispositions = json.loads((out / RELATIVE_PATH).read_text(encoding="utf-8"))
    ledger = read_organize_ledger(out)
    return courses, dispositions, ledger


def _assert_published_unreconciled(courses, dispositions, ledger, plan_uids: list[str]) -> None:
    assert ledger["validated_course_count"] == 1
    assert ledger["technical_quarantine_count"] == 0
    assert len(courses) == 1
    contract = load_course_contract(courses[0].dirs.root)
    data = contract.data
    selected = sorted(item["sop_instance_uid"] for item in data["selected_plans"])
    assert selected == sorted(plan_uids)
    assert data["selected_doses"] == []
    assert data["dose_grid"] is None
    assert data["dose_classification"]["classification"] == UNRECONCILED
    assert data["dose_classification"]["should_sum"] is False
    assert data["dose_classification"]["prescription_plan_uids"] == []
    delivery = data["delivery"]
    assert delivery["prescribed_dose_scope"] == UNRESOLVED_INDEPENDENT_SCOPE
    assert delivery["prescribed_dose_gy"] is None
    assert delivery["resolved_prescribed_dose_total_gy"] is None
    assert delivery["delivered_dose_gy"] is None
    assert delivery["status"] == "delivery_unresolved"
    assert delivery["dose_response_eligible"] is False
    assert delivery["dose_response_ineligibility_reason_code"]
    assert data["dose_completeness"]["status"] != "eligible"
    assert data["dose_completeness"]["unselected_delivered_plan_uids"] == []
    per_plan = {item["plan_sop_uid"]: item for item in delivery["per_plan"]}
    assert set(per_plan) == set(plan_uids)
    assert all(per_plan[uid]["delivered_fraction_count"] > 0 for uid in plan_uids)
    assert all(per_plan[uid]["selected_for_dose_grid"] for uid in plan_uids)
    rows = {row["plan_uid"]: row for row in dispositions["plans"]}
    assert set(rows) == set(plan_uids)
    for uid in plan_uids:
        assert rows[uid]["disposition_type"] == "course_member", rows[uid]
        assert rows[uid]["course_id"] == courses[0].course_id
    assert dispositions["disposition_counts"] == {"course_member": len(plan_uids)}


def test_organizer_publishes_equal_signature_independent_plans_without_false_readiness(tmp_path):
    root, out = tmp_path / "input", tmp_path / "output"
    study_uid, frame_uid, struct_uid = _ids()
    _mk_struct(root / "struct.dcm", struct_uid, study_uid=study_uid, frame_uid=frame_uid, roi_names=["BODY", "PTV1"])
    left_plan, _, left_uid = _plan_and_dose(
        root, "left", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0), with_pixels=True,
    )
    right_plan, _, right_uid = _plan_and_dose(
        root, "right", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(233.0, 0.0, 0.0), with_pixels=True,
    )
    _records(root, "left_rec", left_uid, 5, start=date(2024, 1, 8))
    _records(root, "right_rec", right_uid, 5, start=date(2024, 1, 8))
    before = {path: path.read_bytes() for path in sorted(root.glob("*.dcm"))}

    courses, dispositions, ledger = _run_organizer(root, out)

    _assert_published_unreconciled(courses, dispositions, ledger, [left_uid, right_uid])
    assert {path: path.read_bytes() for path in sorted(root.glob("*.dcm"))} == before


def test_organizer_publishes_strict_subset_concurrent_plans_without_false_readiness(tmp_path):
    root, out = tmp_path / "input", tmp_path / "output"
    study_uid, frame_uid, struct_uid = _ids()
    _mk_struct(root / "struct.dcm", struct_uid, study_uid=study_uid, frame_uid=frame_uid, roi_names=["BODY", "PTV1"])
    _, _, five_uid = _plan_and_dose(
        root, "five", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0), with_pixels=True,
    )
    _, _, three_uid = _plan_and_dose(
        root, "three", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=24.0, fractions=3, isocentre=(0.0, 475.0, 0.0), with_pixels=True,
    )
    _records(root, "five_rec", five_uid, 5, start=date(2024, 1, 8))
    _records(root, "three_rec", three_uid, 3, start=date(2024, 1, 9))

    courses, dispositions, ledger = _run_organizer(root, out)

    _assert_published_unreconciled(courses, dispositions, ledger, [five_uid, three_uid])


def test_organizer_still_publishes_single_delivered_plan_as_eligible_control(tmp_path):
    """Selection changes must not disturb the ordinary single-plan course."""
    root, out = tmp_path / "input", tmp_path / "output"
    study_uid, frame_uid, struct_uid = _ids()
    _mk_struct(root / "struct.dcm", struct_uid, study_uid=study_uid, frame_uid=frame_uid, roi_names=["BODY", "PTV1"])
    _, _, plan_uid = _plan_and_dose(
        root, "only", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0), with_pixels=True,
    )
    _records(root, "rec", plan_uid, 5, start=date(2024, 1, 8))

    courses, dispositions, ledger = _run_organizer(root, out)

    assert ledger["validated_course_count"] == 1
    data = load_course_contract(courses[0].dirs.root).data
    assert [item["sop_instance_uid"] for item in data["selected_plans"]] == [plan_uid]
    assert len(data["selected_doses"]) == 1
    assert data["dose_classification"]["classification"] == "single_dose"
    assert data["delivery"]["prescribed_dose_scope"] == "SINGLE_PLAN_TOTAL"
    assert data["delivery"]["resolved_prescribed_dose_total_gy"] == pytest.approx(25.0)
    assert data["delivery"]["status"] == "fully_delivered"
    assert dispositions["disposition_counts"] == {"course_member": 1}


# --- Round 17 accounting: course fraction totals, resume, scope, clusters ------

UNRESOLVED_INDEPENDENT_SCOPE = "UNRESOLVED_INDEPENDENT_DELIVERY"
WITHHELD_BASIS = "withheld_independent_delivery_unreconciled"


def _record_naming(root: Path, name: str, uids: list[str], *, day: date) -> Path:
    return _record_referencing_both(root, name, uids, day=day)


def _assert_course_fraction_totals_withheld(case_meta: dict, plan_uids: list[str], per_plan_fx: dict[str, int]) -> None:
    """Course totals are null with an explicit basis; per-plan counts stay exact."""
    assert case_meta["delivered_fraction_count"] is None
    assert case_meta["planned_fraction_count"] is None
    assert case_meta["fractions_count"] is None
    assert case_meta["course_fraction_totals_basis"] == WITHHELD_BASIS
    assert "independent" in str(case_meta["course_fraction_totals_reason"]).lower()
    details = {item["plan_sop_uid"]: item for item in case_meta["delivery_plan_details"]}
    assert set(details) == set(plan_uids)
    for uid in plan_uids:
        assert details[uid]["delivered_fraction_count"] == per_plan_fx[uid]
        assert details[uid]["planned_fraction_count"] == per_plan_fx[uid]
    contract = case_meta["course_contract"]
    assert contract["delivery"]["prescribed_dose_scope"] == UNRESOLVED_INDEPENDENT_SCOPE
    assert contract["dose_classification"]["prescribed_dose_scope"] == UNRESOLVED_INDEPENDENT_SCOPE
    assert contract["delivery"]["dose_response_eligible"] is False
    assert contract["dose_grid"] is None
    assert contract["delivery"]["delivered_dose_gy"] is None
    assert contract["delivery"]["resolved_prescribed_dose_total_gy"] is None
    selected = {item["sop_instance_uid"]: item for item in contract["selected_plans"]}
    assert set(selected) == set(plan_uids)
    for uid in plan_uids:
        assert selected[uid]["delivered_fraction_count"] == per_plan_fx[uid]
        assert selected[uid]["planned_fraction_count"] == per_plan_fx[uid]


def test_course_fraction_totals_are_withheld_for_independent_plans_fresh_and_on_resume(tmp_path):
    """Two concurrent 25 Gy / 5 fx targets are not a 10-fraction, 10-planned course.

    Fresh publication and resume hydration must both withhold the course
    fraction totals with a stated basis, keep every plan in membership with
    its exact per-plan counts, and keep the course dose-response ineligible.
    """
    import pandas as pd

    root, out = tmp_path / "input", tmp_path / "output"
    study_uid, frame_uid, struct_uid = _ids()
    _mk_struct(root / "struct.dcm", struct_uid, study_uid=study_uid, frame_uid=frame_uid, roi_names=["BODY", "PTV1"])
    _, _, left_uid = _plan_and_dose(
        root, "left", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0), with_pixels=True,
    )
    _, _, right_uid = _plan_and_dose(
        root, "right", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(233.0, 0.0, 0.0), with_pixels=True,
    )
    _records(root, "left_rec", left_uid, 5, start=date(2024, 1, 8))
    _records(root, "right_rec", right_uid, 5, start=date(2024, 1, 8))
    plan_uids = [left_uid, right_uid]
    per_plan_fx = {left_uid: 5, right_uid: 5}

    courses, dispositions, ledger = _run_organizer(root, out)
    _assert_published_unreconciled(courses, dispositions, ledger, plan_uids)
    assert courses[0].delivered_fraction_count is None
    assert courses[0].planned_fraction_count is None
    course_dir = courses[0].dirs.root
    meta_path = course_dir / "metadata" / "case_metadata.json"
    fresh_meta = json.loads(meta_path.read_text(encoding="utf-8"))
    _assert_course_fraction_totals_withheld(fresh_meta, plan_uids, per_plan_fx)
    # The per-record tables keep every membership plan's records, tagged by plan.
    raw = pd.read_excel(course_dir / "metadata" / "fractions_raw.xlsx")
    assert sorted(raw["plan_sop"].astype(str).unique()) == sorted(plan_uids)
    assert len(raw) == 10
    aggregated = pd.read_excel(course_dir / "fractions.xlsx")
    assert sorted(aggregated["plan_sop"].astype(str).unique()) == sorted(plan_uids)
    assert aggregated.groupby("plan_sop").size().to_dict() == per_plan_fx
    fresh_contract = load_course_contract(course_dir).data

    # Resume hydration must not re-derive a summed course total.
    hydrated = org._hydrate_existing_course(courses[0].patient_id, courses[0].course_key, course_dir)
    assert hydrated is not None
    assert hydrated.delivered_fraction_count is None
    assert hydrated.planned_fraction_count is None
    assert sorted(item["sop_instance_uid"] for item in hydrated.selected_plan_contract) == sorted(plan_uids)
    assert hydrated.selected_dose_contract == []
    assert hydrated.delivery_status == "delivery_unresolved"
    assert hydrated.delivered_dose_gy is None

    config = PipelineConfig(
        root, out, out.parent / "logs", max_workers_override=1,
        dicom_copy_use_hardlinks=False, dicom_copy_dedup_by_sop_uid=False, resume=True,
    )
    resumed = org.organize_and_merge(config)
    assert len(resumed) == 1
    assert resumed[0].delivered_fraction_count is None
    assert resumed[0].planned_fraction_count is None
    resumed_meta = json.loads(meta_path.read_text(encoding="utf-8"))
    _assert_course_fraction_totals_withheld(resumed_meta, plan_uids, per_plan_fx)
    resumed_contract = load_course_contract(course_dir).data
    for key in ("selected_plans", "selected_doses", "dose_grid", "dose_classification"):
        assert resumed_contract[key] == fresh_contract[key]
    for key in ("prescribed_dose_scope", "prescribed_dose_gy", "resolved_prescribed_dose_total_gy",
                "delivered_dose_gy", "status", "dose_response_eligible", "per_plan"):
        assert resumed_contract["delivery"][key] == fresh_contract["delivery"][key]
    resumed_dispositions = json.loads((out / RELATIVE_PATH).read_text(encoding="utf-8"))
    assert resumed_dispositions["disposition_counts"] == {"course_member": 2}
    assert read_organize_ledger(out)["validated_course_count"] == 1


def test_ordinary_single_plan_course_keeps_summed_fraction_totals_with_basis(tmp_path):
    root, out = tmp_path / "input", tmp_path / "output"
    study_uid, frame_uid, struct_uid = _ids()
    _mk_struct(root / "struct.dcm", struct_uid, study_uid=study_uid, frame_uid=frame_uid, roi_names=["BODY", "PTV1"])
    _, _, plan_uid = _plan_and_dose(
        root, "only", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0), with_pixels=True,
    )
    _records(root, "rec", plan_uid, 5, start=date(2024, 1, 8))

    courses, _, _ = _run_organizer(root, out)

    meta = json.loads((courses[0].dirs.root / "metadata" / "case_metadata.json").read_text(encoding="utf-8"))
    assert meta["delivered_fraction_count"] == 5
    assert meta["planned_fraction_count"] == 5
    assert meta["fractions_count"] == 5
    assert meta["course_fraction_totals_basis"] == "selected_membership_sum"
    assert meta["course_fraction_totals_reason"] is None
    hydrated = org._hydrate_existing_course(courses[0].patient_id, courses[0].course_key, courses[0].dirs.root)
    assert hydrated is not None
    assert hydrated.delivered_fraction_count == 5
    assert hydrated.planned_fraction_count == 5


def test_unreconciled_scope_is_dedicated_and_accepted_by_the_contract_validator():
    from rtpipeline import course_contract as cc

    assert org.INDEPENDENT_DELIVERY_UNRESOLVED_SCOPE == UNRESOLVED_INDEPENDENT_SCOPE
    assert UNRESOLVED_INDEPENDENT_SCOPE.startswith("UNRESOLVED_")
    assert UNRESOLVED_INDEPENDENT_SCOPE in cc.ALLOWED_PRESCRIBED_DOSE_SCOPES
    assert "UNRESOLVED_REPLACEMENT_CHAIN" in cc.ALLOWED_PRESCRIBED_DOSE_SCOPES


# --- Cluster semantics: shared records do not prove equivalence -----------------


def _equal_signature_plans(root: Path, names: list[str]):
    study_uid, frame_uid, struct_uid = _ids()
    plans, doses, uids = [], [], []
    for index, name in enumerate(names):
        plan, dose, uid = _plan_and_dose(
            root, name, struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
            plan_date=f"202401{index + 1:02d}", rx_gy=25.0, fractions=5, isocentre=(float(index) * 100.0, 0.0, 0.0),
        )
        plans.append(plan); doses.append(dose); uids.append(uid)
    return plans, doses, uids


def test_partial_record_overlap_with_exclusive_instances_is_not_one_revision(tmp_path):
    """A and B each have exclusive records and also share two; neither is a revision of the other."""
    (plan_a, plan_b), (dose_a, dose_b), (uid_a, uid_b) = _equal_signature_plans(tmp_path, ["a", "b"])
    records = _records(tmp_path, "a_only", uid_a, 3, start=date(2024, 1, 8))
    records += _records(tmp_path, "b_only", uid_b, 3, start=date(2024, 1, 15))
    records += [
        _record_naming(tmp_path, f"shared_{index}", [uid_a, uid_b], day=date(2024, 1, 22) + timedelta(days=index))
        for index in range(2)
    ]

    classified = org._classify_doses([plan_a, plan_b], [dose_a, dose_b], treatment_record_paths=records)

    _assert_unreconciled(classified, [plan_a, plan_b])
    assert not any("De-duplicated" in warning for warning in classified.warnings)


@pytest.mark.parametrize("plan_order", [(0, 1, 2), (2, 1, 0), (1, 2, 0), (0, 2, 1), (2, 0, 1), (1, 0, 2)])
@pytest.mark.parametrize("reverse_records", [False, True])
def test_transitive_three_plan_overlap_retains_every_plan_under_permutation(tmp_path, plan_order, reverse_records):
    """A~B and B~C share single records while each plan keeps exclusive deliveries.

    Single-link clustering would merge all three and keep one representative,
    discarding two plans' exclusive delivery evidence. Every plan is retained
    under the unreconciled hold regardless of input order.
    """
    plans, doses, uids = _equal_signature_plans(tmp_path, ["a", "b", "c"])
    records = []
    for index, uid in enumerate(uids):
        records += _records(tmp_path, f"{index}_only", uid, 2, start=date(2024, 1, 8 + 3 * index))
    records.append(_record_naming(tmp_path, "ab", [uids[0], uids[1]], day=date(2024, 2, 1)))
    records.append(_record_naming(tmp_path, "bc", [uids[1], uids[2]], day=date(2024, 2, 2)))
    if reverse_records:
        records = list(reversed(records))
    ordered_plans = [plans[i] for i in plan_order]
    ordered_doses = [doses[i] for i in plan_order]

    classified = org._classify_doses(ordered_plans, ordered_doses, treatment_record_paths=records)

    _assert_unreconciled(classified, plans)


def _physical_equal_signature_plans(root: Path, names: list[str]):
    """Equal 25 Gy / 5 fx plans with complete beam evidence and isocentres
    100 mm apart per plan: physically different targets, fully provable."""
    plans, doses, uids = _equal_signature_plans(root, names)
    for index, plan in enumerate(plans):
        _physical_beam(plan, isocentre=(float(index) * 100.0, 0.0, 0.0))
    return plans, doses, uids


@pytest.mark.parametrize("plan_order", [(0, 1), (1, 0)])
def test_nested_record_sets_with_different_isocentres_are_held(tmp_path, plan_order):
    """Every record of B also names A, yet B's isocentre is 100 mm from A's.

    Record coverage does not prove the plans equivalent, so B is retained as
    membership under the hold instead of being erased behind A.
    """
    (plan_a, plan_b), (dose_a, dose_b), (uid_a, uid_b) = _physical_equal_signature_plans(tmp_path, ["a", "b"])
    records = [
        _record_naming(tmp_path, f"both_{index}", [uid_a, uid_b], day=date(2024, 1, 8) + timedelta(days=index))
        for index in range(3)
    ]
    records += _records(tmp_path, "a_only", uid_a, 2, start=date(2024, 1, 11))
    plans = [[plan_a, plan_b][i] for i in plan_order]
    doses = [[dose_a, dose_b][i] for i in plan_order]

    classified = org._classify_doses(plans, doses, treatment_record_paths=records)

    _assert_unreconciled(classified, [plan_a, plan_b])
    assert not any("De-duplicated" in warning for warning in classified.warnings)
    assert any(
        uid_b in warning and "not proven physically equivalent" in warning
        for warning in classified.warnings
    )


@pytest.mark.parametrize("plan_order", [(0, 1), (1, 0)])
def test_nested_record_sets_without_strict_proof_are_held(tmp_path, plan_order):
    """Nested records with no machine, meterset or control-point evidence:
    missing proof is not equivalence."""
    (plan_a, plan_b), (dose_a, dose_b), (uid_a, uid_b) = _equal_signature_plans(tmp_path, ["a", "b"])
    records = [
        _record_naming(tmp_path, f"both_{index}", [uid_a, uid_b], day=date(2024, 1, 8) + timedelta(days=index))
        for index in range(3)
    ]
    records += _records(tmp_path, "a_only", uid_a, 2, start=date(2024, 1, 11))
    plans = [[plan_a, plan_b][i] for i in plan_order]
    doses = [[dose_a, dose_b][i] for i in plan_order]

    classified = org._classify_doses(plans, doses, treatment_record_paths=records)

    _assert_unreconciled(classified, [plan_a, plan_b])
    assert not any("De-duplicated" in warning for warning in classified.warnings)


@pytest.mark.parametrize("plan_order", [(0, 1), (1, 0)])
def test_nested_record_sets_with_strict_physical_proof_keep_the_covering_plan(tmp_path, plan_order):
    """Positive control: B is a proven re-export of A and every record naming
    B also names A. A covers all delivery and represents both."""
    study_uid, frame_uid, struct_uid = _ids()
    plan_a, dose_a, uid_a = _plan_and_dose(
        tmp_path, "a", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(5.0, 5.0, 5.0),
    )
    _physical_beam(plan_a, isocentre=(5.0, 5.0, 5.0))
    plan_b, dose_b, uid_b = _strict_equivalent_copy(tmp_path, plan_a, "b")
    records = [
        _record_naming(tmp_path, f"both_{index}", [uid_a, uid_b], day=date(2024, 1, 8) + timedelta(days=index))
        for index in range(3)
    ]
    records += _records(tmp_path, "a_only", uid_a, 2, start=date(2024, 1, 11))
    plans = [[plan_a, plan_b][i] for i in plan_order]
    doses = [[dose_a, dose_b][i] for i in plan_order]

    classified = org._classify_doses(plans, doses, treatment_record_paths=records)

    assert classified.classification == "plan_revisions_deduplicated"
    assert classified.selected_plans == [plan_a]
    assert classified.selected_doses == [dose_a]
    assert classified.excluded_doses == [dose_b]


@pytest.mark.parametrize("plan_order", [(0, 1, 2), (2, 1, 0), (1, 2, 0), (0, 2, 1), (2, 0, 1), (1, 0, 2)])
def test_transitively_nested_record_sets_with_different_isocentres_are_held(tmp_path, plan_order):
    """A ⊆ B ⊆ C by record instances, isocentres 100 mm apart: C covers every
    delivery instance but is not proven physically equivalent to A or B, so all
    three stay membership under the hold in every input order."""
    plans, doses, uids = _physical_equal_signature_plans(tmp_path, ["a", "b", "c"])
    records = [
        _record_naming(tmp_path, f"abc_{index}", uids, day=date(2024, 1, 8) + timedelta(days=index))
        for index in range(3)
    ]
    records.append(_record_naming(tmp_path, "bc", [uids[1], uids[2]], day=date(2024, 1, 11)))
    records += _records(tmp_path, "c_only", uids[2], 1, start=date(2024, 1, 12))
    ordered_plans = [plans[i] for i in plan_order]
    ordered_doses = [doses[i] for i in plan_order]

    classified = org._classify_doses(ordered_plans, ordered_doses, treatment_record_paths=records)

    _assert_unreconciled(classified, plans)
    assert not any("De-duplicated" in warning for warning in classified.warnings)


@pytest.mark.parametrize("plan_order", [(0, 1, 2), (2, 1, 0), (1, 2, 0), (0, 2, 1), (2, 0, 1), (1, 0, 2)])
def test_transitively_nested_proven_re_exports_keep_the_covering_plan(tmp_path, plan_order):
    """Positive control: A and B are proven re-exports of C with nested
    records; C covers every delivery, nothing physical is lost."""
    study_uid, frame_uid, struct_uid = _ids()
    plan_c, dose_c, uid_c = _plan_and_dose(
        tmp_path, "c", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240103", rx_gy=25.0, fractions=5, isocentre=(1.0, 2.0, 3.0),
    )
    _physical_beam(plan_c, isocentre=(1.0, 2.0, 3.0))
    plan_a, dose_a, uid_a = _strict_equivalent_copy(tmp_path, plan_c, "a", plan_date="20240101")
    plan_b, dose_b, uid_b = _strict_equivalent_copy(tmp_path, plan_c, "b", plan_date="20240102")
    plans, doses, uids = [plan_a, plan_b, plan_c], [dose_a, dose_b, dose_c], [uid_a, uid_b, uid_c]
    records = [
        _record_naming(tmp_path, f"abc_{index}", uids, day=date(2024, 1, 8) + timedelta(days=index))
        for index in range(3)
    ]
    records.append(_record_naming(tmp_path, "bc", [uid_b, uid_c], day=date(2024, 1, 11)))
    records += _records(tmp_path, "c_only", uid_c, 1, start=date(2024, 1, 12))
    ordered_plans = [plans[i] for i in plan_order]
    ordered_doses = [doses[i] for i in plan_order]

    classified = org._classify_doses(ordered_plans, ordered_doses, treatment_record_paths=records)

    assert classified.classification == "plan_revisions_deduplicated"
    assert classified.selected_plans == [plan_c]
    assert classified.selected_doses == [dose_c]
    assert sorted(map(str, classified.excluded_doses)) == sorted(map(str, [dose_a, dose_b]))


def test_proven_re_export_collapses_while_unproven_sibling_is_held(tmp_path):
    """Mixed nested component: B is a proven re-export of covering plan A, C
    shares A's records but sits 100 mm away. B contributes through A; C stays
    membership and the course is held."""
    study_uid, frame_uid, struct_uid = _ids()
    plan_a, dose_a, uid_a = _plan_and_dose(
        tmp_path, "a", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    _physical_beam(plan_a, isocentre=(0.0, 0.0, 0.0))
    plan_b, dose_b, uid_b = _strict_equivalent_copy(tmp_path, plan_a, "b", plan_date="20231231")
    plan_c, dose_c, uid_c = _plan_and_dose(
        tmp_path, "c", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(100.0, 0.0, 0.0),
    )
    _physical_beam(plan_c, isocentre=(100.0, 0.0, 0.0))
    records = [
        _record_naming(tmp_path, f"abc_{index}", [uid_a, uid_b, uid_c], day=date(2024, 1, 8) + timedelta(days=index))
        for index in range(3)
    ]
    records += _records(tmp_path, "a_only", uid_a, 2, start=date(2024, 1, 11))

    classified = org._classify_doses([plan_a, plan_b, plan_c], [dose_a, dose_b, dose_c], treatment_record_paths=records)

    _assert_unreconciled(classified, [plan_a, plan_c])
    assert any(uid_c in warning and "not proven physically equivalent" in warning for warning in classified.warnings)
    assert not any(uid_b in warning and "not proven" in warning for warning in classified.warnings)


def test_organizer_holds_nested_record_plans_with_different_isocentres(tmp_path):
    """Public organizer path: nested records over physically different plans
    publish both as membership under the explicit hold with exact per-plan
    counts and null course fraction totals, never a de-duplicated grid."""
    root, out = tmp_path / "input", tmp_path / "output"
    study_uid, frame_uid, struct_uid = _ids()
    _mk_struct(root / "struct.dcm", struct_uid, study_uid=study_uid, frame_uid=frame_uid, roi_names=["BODY", "PTV1"])
    plan_a, _, uid_a = _plan_and_dose(
        root, "a", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0), with_pixels=True,
    )
    _physical_beam(plan_a, isocentre=(0.0, 0.0, 0.0))
    plan_b, _, uid_b = _plan_and_dose(
        root, "b", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240102", rx_gy=25.0, fractions=5, isocentre=(100.0, 0.0, 0.0), with_pixels=True,
    )
    _physical_beam(plan_b, isocentre=(100.0, 0.0, 0.0))
    for index in range(3):
        _record_naming(root, f"both_{index}", [uid_a, uid_b], day=date(2024, 1, 8) + timedelta(days=index))
    _records(root, "a_only", uid_a, 2, start=date(2024, 1, 11))

    courses, dispositions, ledger = _run_organizer(root, out)

    _assert_published_unreconciled(courses, dispositions, ledger, [uid_a, uid_b])
    assert courses[0].delivered_fraction_count is None
    assert courses[0].planned_fraction_count is None
    meta = json.loads((courses[0].dirs.root / "metadata" / "case_metadata.json").read_text(encoding="utf-8"))
    assert meta["delivered_fraction_count"] is None
    assert meta["planned_fraction_count"] is None
    assert meta["course_fraction_totals_basis"] == WITHHELD_BASIS
    details = {item["plan_sop_uid"]: item for item in meta["delivery_plan_details"]}
    assert details[uid_a]["delivered_fraction_count"] == 5
    assert details[uid_b]["delivered_fraction_count"] == 3
    assert details[uid_a]["planned_fraction_count"] == 5
    assert details[uid_b]["planned_fraction_count"] == 5
    warnings = " ".join(meta["course_contract"]["dose_classification"].get("warnings", []))
    assert "not proven physically equivalent" in warnings
    assert "De-duplicated" not in warnings


@pytest.mark.parametrize("changed_field", ["isocentre", "machine", "control_points", "target_uid", "frame", "structure"])
def test_one_source_proof_change_prevents_shared_record_collapse(tmp_path, changed_field):
    """Change only one field from a proven copy, avoiding confounded negatives."""
    study_uid, frame_uid, struct_uid = _ids()
    plan_a, dose_a, uid_a = _plan_and_dose(
        tmp_path, "a", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    _physical_beam(plan_a, isocentre=(0.0, 0.0, 0.0))
    plan_b, dose_b, uid_b = _strict_equivalent_copy(tmp_path, plan_a, "b")
    a = {"path": plan_a, "sop_uid": uid_a}
    b = {"path": plan_b, "sop_uid": uid_b}
    assert org._strict_plan_equivalence(b, a)[0] is True
    ds = pydicom.dcmread(plan_b)
    if changed_field == "isocentre":
        for cp in ds.BeamSequence[0].ControlPointSequence:
            cp.IsocenterPosition = [100.0, 0.0, 0.0]
    elif changed_field == "machine":
        del ds.BeamSequence[0].TreatmentMachineName
    elif changed_field == "control_points":
        del ds.BeamSequence[0].ControlPointSequence
    elif changed_field == "target_uid":
        ds.DoseReferenceSequence[0].DoseReferenceUID = generate_uid()
    elif changed_field == "frame":
        ds.FrameOfReferenceUID = generate_uid()
    else:
        ds.ReferencedStructureSetSequence[0].ReferencedSOPInstanceUID = generate_uid()
    ds.save_as(plan_b, enforce_file_format=True)
    equivalent, reason = org._strict_plan_equivalence(b, a)
    assert equivalent is False
    assert reason
    records = [
        _record_naming(tmp_path, f"shared_{i}", [uid_a, uid_b], day=date(2024, 1, 8) + timedelta(days=i))
        for i in range(3)
    ]
    records += _records(tmp_path, "a_only", uid_a, 2, start=date(2024, 1, 11))
    classified = org._classify_doses([plan_a, plan_b], [dose_a, dose_b], treatment_record_paths=records)
    _assert_unreconciled(classified, [plan_a, plan_b])


def test_same_uid_equivalence_requires_identical_source_bytes(tmp_path):
    study_uid, frame_uid, struct_uid = _ids()
    plan_a, _, uid = _plan_and_dose(
        tmp_path, "a", struct_uid=struct_uid, study_uid=study_uid, frame_uid=frame_uid,
        plan_date="20240101", rx_gy=25.0, fractions=5, isocentre=(0.0, 0.0, 0.0),
    )
    plan_b = tmp_path / "copy.dcm"
    plan_b.write_bytes(plan_a.read_bytes())
    a, b = {"path": plan_a, "sop_uid": uid}, {"path": plan_b, "sop_uid": uid}
    assert org._strict_plan_equivalence(b, a)[0] is True
    ds = pydicom.dcmread(plan_b)
    ds.RTPlanLabel = "CHANGED"
    ds.save_as(plan_b, enforce_file_format=True)
    assert org._strict_plan_equivalence(b, a) == (
        False, "same SOPInstanceUID with different source bytes"
    )
