#!/bin/bash

# Auto-Build Environment Setup - RTpipeline Scientific Code Review
# Generated by Planner Agent

set -e

echo "========================================"
echo "RTpipeline Code Review Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Python
if command -v python &> /dev/null; then
    echo -e "${GREEN}Python found:${NC} $(python --version)"
else
    echo -e "${RED}Python not found${NC}"
    exit 1
fi

# Check if in project directory
if [ ! -f "CLAUDE.md" ] || [ ! -d "rtpipeline" ]; then
    echo -e "${RED}Not in rtpipeline project root${NC}"
    echo "Please run from project root directory"
    exit 1
fi
echo -e "${GREEN}Project directory verified${NC}"

# Check conda (optional but recommended)
if command -v conda &> /dev/null; then
    echo -e "${GREEN}Conda found:${NC} $(conda --version)"
else
    echo -e "${YELLOW}Conda not found - some features may be limited${NC}"
fi

# Check Docker (optional)
if command -v docker &> /dev/null; then
    echo -e "${GREEN}Docker found:${NC} $(docker --version | head -1)"
else
    echo -e "${YELLOW}Docker not found - Docker tests will be skipped${NC}"
fi

# ============================================
# VERIFY KEY FILES EXIST
# ============================================

echo ""
echo "Verifying key files..."

KEY_FILES=(
    "rtpipeline/dvh.py"
    "rtpipeline/radiomics.py"
    "rtpipeline/radiomics_robustness.py"
    "rtpipeline/custom_structures.py"
    "rtpipeline/segmentation.py"
    "rtpipeline/organize.py"
    "rtpipeline/quality_control.py"
    "rtpipeline/config.py"
    "Snakefile"
    "config.yaml"
)

all_present=true
for file in "${KEY_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo -e "${GREEN}✓${NC} $file"
    else
        echo -e "${RED}✗${NC} $file (missing)"
        all_present=false
    fi
done

if [ "$all_present" = false ]; then
    echo -e "${YELLOW}Warning: Some key files are missing${NC}"
fi

# ============================================
# CHECK TESTS
# ============================================

echo ""
echo "Checking test setup..."

if [ -d "tests" ]; then
    test_count=$(find tests -name "test_*.py" | wc -l | tr -d ' ')
    echo -e "${GREEN}Found ${test_count} test files in tests/${NC}"
else
    echo -e "${YELLOW}No tests directory found${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Code Review"
echo "========================================"
echo ""
echo "Review Stages:"
echo "  1. DICOM Organization (organize.py)"
echo "  2. CT Processing (ct.py)"
echo "  3. Segmentation (segmentation.py)"
echo "  4. Custom Models (custom_models.py)"
echo "  5. Custom Structures (custom_structures.py)"
echo "  6. CT Cropping (anatomical_cropping.py)"
echo "  7. DVH Analysis (dvh.py)"
echo "  8. Radiomics Extraction (radiomics.py)"
echo "  9. Robustness Analysis (radiomics_robustness.py)"
echo "  10. Quality Control (quality_control.py)"
echo "  11. Aggregation (scripts/)"
echo "  12. Configuration (config.py)"
echo ""
echo "Scientific Standards to Validate:"
echo "  - IBSI compliance for radiomics"
echo "  - AAPM/RTOG guidelines for DVH"
echo "  - ICC(3,1) via pingouin for robustness"
echo ""
echo "Note: This is a manual code review task."
echo "No services need to be started."
echo ""
echo "To run tests: pytest"
echo "To verify Snakemake: snakemake -n --configfile config.yaml"
echo ""
